### ISSUE TITLE
`gsub': invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by henkvalk** [JeroenBoersma/docker-compose-development#160]
```
docker-sync start                
/Users/henkvalk/.gem/ruby/2.6.0/gems/dotenv-2.7.6/lib/dotenv/parser.rb:48:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)
	from /Users/henkvalk/.gem/ruby/2.6.0/gems/dotenv-2.7.6/lib/dotenv/parser.rb:48:in `call'
	from /Users/henkvalk/.gem/ruby/2.6.0/gems/dotenv-2.7.6/lib/dotenv/parser.rb:36:in `call'
	from /Users/henkvalk/.gem/ruby/2.6.0/gems/dotenv-2.7.6/lib/dotenv/environment.rb:13:in `load'
	from /Users/henkvalk/.gem/ruby/2.6.0/gems/dotenv-2.7.6/lib/dotenv/environment.rb:9:in `initialize'
	from /Users/henkvalk/.gem/ruby/2.6.0/gems/dotenv-2.7.6/lib/dotenv.rb:16:in `new'
	from /Users/henkvalk/.gem/ruby/2.6.0/gems/dotenv-2.7.6/lib/dotenv.rb:16:in `block (2 levels) in load'
	from /Users/henkvalk/.gem/ruby/2.6.0/gems/dotenv-2.7.6/lib/dotenv.rb:83:in `ignoring_nonexistent_files'
	from /Users/henkvalk/.gem/ruby/2.6.0/gems/dotenv-2.7.6/lib/dotenv.rb:15:in `block in load'
	from /Users/henkvalk/.gem/ruby/2.6.0/gems/dotenv-2.7.6/lib/dotenv.rb:64:in `block in with'
	from /Users/henkvalk/.gem/ruby/2.6.0/gems/dotenv-2.7.6/lib/dotenv.rb:63:in `each'
	from /Users/henkvalk/.gem/ruby/2.6.0/gems/dotenv-2.7.6/lib/dotenv.rb:63:in `reduce'
	from /Users/henkvalk/.gem/ruby/2.6.0/gems/dotenv-2.7.6/lib/dotenv.rb:63:in `with'
	from /Users/henkvalk/.gem/ruby/2.6.0/gems/dotenv-2.7.6/lib/dotenv.rb:14:in `load'
	from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/config/config_serializer.rb:52:in `load_dotenv'
	from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/config/config_serializer.rb:27:in `expand_env_variables'
	from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/config/config_serializer.rb:17:in `default_deserializer_string'
	from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/config/config_serializer.rb:11:in `default_deserializer_file'
	from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/config/global_config.rb:35:in `load_global_config'
	from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/config/global_config.rb:29:in `initialize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/singleton.rb:141:in `new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/singleton.rb:141:in `block in instance'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/singleton.rb:139:in `synchronize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/singleton.rb:139:in `instance'
	from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/config/global_config.rb:26:in `load'
	from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/update_check.rb:11:in `initialize'
	from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/tasks/sync/sync.thor:32:in `new'
	from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/tasks/sync/sync.thor:32:in `start'
	from /Users/henkvalk/.gem/ruby/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /Users/henkvalk/.gem/ruby/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/henkvalk/.gem/ruby/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /Users/henkvalk/.gem/ruby/2.6.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/bin/docker-sync:14:in `<top (required)>'
	from /usr/local/bin/docker-sync:23:in `load'
	from /usr/local/bin/docker-sync:23:in `<main>'

```

**Comment by henkvalk** [comment]
edit file: `~/.gem/ruby/2.6.0/gems/dotenv-2.7.6/lib/dotenv/parser.rb` line 48 
```
lines = @string.gsub(/\r\n?/, "\n")`
```

```
if ! @string.valid_encoding?
    s = @string.encode("UTF-16be", :invalid=>:replace, :replace=>"?").encode('UTF-8')
    lines = s.gsub(/\r\n?/, "\n")
end
```
